#!/bin/bash

#L13 TLS1.2 Cipher list ECDHE-RSA-AES128-SHA ECDHE-RSA-AES128-SHA256 DHE-RSA-AES256-SHA DHE-RSA-AES128-SHA DES-CBC3-SHA AES256-SHA256 AES128-SHA AES128-SHA256

Ciphers="ECDHE-RSA-AES128-SHA ECDHE-RSA-AES128-SHA256 DHE-RSA-AES256-SHA DHE-RSA-AES128-SHA DES-CBC3-SHA AES256-SHA256 AES128-SHA AES128-SHA256"

echo Checking ciphers at $1

for cipher in $Ciphers
do
        echo | /opt/openssl-1.0.2/bin/openssl s_client -connect $1 -tls1_2 -cipher $cipher 2>/dev/null | grep New,
done
